Added 'stop' command.

diff --git a/basiliskiivm b/basiliskiivm
--- a/basiliskiivm
+++ b/basiliskiivm
@@ -40,8 +40,9 @@ function usage() {
 	echo "Commands:"
 	echo " package       : package the current BasiliskII configuration into"
 	echo "                 a .BasiliskIIVM package"
-	echo " start <path>  : start a BasiliskII instance running from a"
+	echo " start <vm>    : start a BasiliskII instance running from a"
 	echo "                 .BasiliskIIVM package"
+	echo " stop <vm>     : stop a running BasiliskII instance"
 	echo
 }
 
@@ -171,6 +172,22 @@ function vm_start() {
 	$success
 }
 
+function vm_stop() {
+	local success=false
+	
+	local vm="$(vm_pkg_name "$1")"
+	if [ -n "$vm" ]; then
+		if ! vm_is_running "$1"; then
+			echo "Error! The '$vm' BasiliskII VM is not running."
+		else
+			echo "Warning! It is not safe to stop the '$vm' BasiliskII VM while it is running."
+			echo "Please choose Special > Shutdown from within the BasiliskII VM instance to shut it down."
+		fi
+	fi
+	
+	$success
+}
+
 function main() {
 	case "$1" in
 		"-h" | "--help")
@@ -184,6 +201,10 @@ function main() {
 		"start")
 			shift
 			vm_start "$1"
+			;;
+		"stop")
+			shift
+			vm_stop "$1"
 			;;
 		"package")
 			shift
